CREATE DATABASE IF NOT EXISTS dogdb;
USE dogdb;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(50),
  address VARCHAR(255),
  phone VARCHAR(20),
  email VARCHAR(100),
  birthdate DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
